import { Question } from '../models/Question.js';

export const seedTechnicalMCQs = async () => {
  const count = await Question.countDocuments({ category: 'technical-mcq' });
  if (count > 0) {
    console.log(`Skipping technical-mcq seed, ${count} questions already exist.`);
    return;
  }

  const questions = [
    // --- C/C++ Basics (10 questions) ---
    {
      category: 'technical-mcq',
      topic: 'C/C++ Basics',
      subtopic: 'Pointers',
      difficulty: 'medium',
      question: 'What is the size of a pointer in a 32-bit system?',
      options: ['2 bytes', '4 bytes', '8 bytes', 'Depends on data type'],
      answer: 1,
      explanation: 'In a 32-bit architecture, pointers are always 4 bytes (32 bits) in size, regardless of what data type they point to, as memory addresses are 32 bits long.',
      whyOthersWrong: '2 bytes is for 16-bit systems. 8 bytes is for 64-bit systems. Pointer size does not depend on the data type it points to.',
      tags: ['pointers', 'memory', 'sizeof'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'C/C++ Basics',
      subtopic: 'Macros',
      difficulty: 'medium',
      question: 'Which of the following is executed before compilation?',
      options: ['Inline functions', 'Macros', 'Templates', 'Virtual functions'],
      answer: 1,
      explanation: 'Macros are handled by the C/C++ preprocessor, which runs before the actual compilation phase. It does simple text substitution.',
      whyOthersWrong: 'Inline functions, templates, and virtual functions are resolved and handled during the compilation phase or at runtime (virtual functions).',
      tags: ['macros', 'preprocessor'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'C/C++ Basics',
      subtopic: 'Memory Allocation',
      difficulty: 'easy',
      question: 'Which function is used to reallocate memory in C?',
      options: ['malloc()', 'calloc()', 'realloc()', 'free()'],
      answer: 2,
      explanation: 'realloc() changes the size of the memory block pointed to by a previously allocated pointer.',
      whyOthersWrong: 'malloc() allocates uninitialized memory. calloc() allocates zero-initialized memory. free() deallocates memory.',
      tags: ['memory-allocation', 'c'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'C/C++ Basics',
      subtopic: 'Storage Classes',
      difficulty: 'medium',
      question: 'What is the default initial value of a static local variable in C?',
      options: ['Garbage value', '0', '1', 'Null'],
      answer: 1,
      explanation: 'Variables declared with static storage class are automatically initialized to zero if not explicitly initialized.',
      whyOthersWrong: 'Local auto variables have garbage value. Pointers might default to Null if global/static, but 0 is the general numeric default. 1 is incorrect.',
      tags: ['storage-classes', 'static'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'C/C++ Basics',
      subtopic: 'Memory Allocation',
      difficulty: 'medium',
      question: 'In C++, what does the `new` operator do that `malloc` does not?',
      options: ['Returns a void pointer', 'Calls the constructor', 'Allocates memory on the heap', 'Requires explicit type casting'],
      answer: 1,
      explanation: 'The `new` operator in C++ allocates memory and also calls the class constructor to initialize the object. `malloc` only allocates raw memory.',
      whyOthersWrong: '`malloc` returns a void pointer, `new` returns a typed pointer. Both allocate on the heap. `malloc` requires casting in C++, `new` does not.',
      tags: ['memory-allocation', 'cpp'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'C/C++ Basics',
      subtopic: 'Pointers',
      difficulty: 'hard',
      question: 'What does `void *` signify in C?',
      options: ['A pointer that points to nothing', 'A pointer to a function', 'A generic pointer that can point to any data type', 'A null pointer'],
      answer: 2,
      explanation: 'A `void *` is a generic pointer. It has no associated data type, so it can hold the address of any type of variable and can be typecast to any type.',
      whyOthersWrong: 'A null pointer points to memory location 0. A pointer to nothing doesn\'t exist (uninitialized pointers point to garbage).',
      tags: ['pointers', 'void'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'C/C++ Basics',
      subtopic: 'Scope',
      difficulty: 'medium',
      question: 'Which operator is used to access a global variable when a local variable has the same name in C++?',
      options: ['::', '->', '.', '&'],
      answer: 0,
      explanation: 'The scope resolution operator (::) is used to access global variables when a local variable with the same name is hiding it.',
      whyOthersWrong: '`->` accesses members via pointer. `.` accesses members directly. `&` gets the address of a variable.',
      tags: ['scope', 'operators'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'C/C++ Basics',
      subtopic: 'Type Casting',
      difficulty: 'hard',
      question: 'Which C++ cast should be used to cast away constness?',
      options: ['static_cast', 'dynamic_cast', 'const_cast', 'reinterpret_cast'],
      answer: 2,
      explanation: '`const_cast` is explicitly designed to add or remove the `const` qualifier from a variable.',
      whyOthersWrong: 'static_cast is for standard conversions. dynamic_cast is for safe downcasting in inheritance. reinterpret_cast changes the pointer type blindly.',
      tags: ['type-casting', 'const'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 3,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'C/C++ Basics',
      subtopic: 'Macros',
      difficulty: 'medium',
      question: 'What is the output of macro `#define SQUARE(x) x*x` when called with `SQUARE(3+2)`?',
      options: ['25', '11', '10', 'Compilation Error'],
      answer: 1,
      explanation: 'Macros perform literal text substitution. SQUARE(3+2) expands to 3+2*3+2, which evaluates to 3+6+2 = 11.',
      whyOthersWrong: '25 would be if it evaluated (3+2)*(3+2). This demonstrates why macros should use parentheses: `#define SQUARE(x) ((x)*(x))`',
      tags: ['macros', 'trap'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'C/C++ Basics',
      subtopic: 'Storage Classes',
      difficulty: 'easy',
      question: 'Which storage class is used to hint to the compiler that a variable will be heavily used and should be kept in a CPU register?',
      options: ['auto', 'extern', 'register', 'static'],
      answer: 2,
      explanation: 'The `register` keyword suggests to the compiler to store the variable in a CPU register for faster access.',
      whyOthersWrong: '`auto` is default local scope. `extern` is for global visibility. `static` preserves value between function calls.',
      tags: ['storage-classes', 'performance'],
      sourceType: 'capgemini-style',
      relevance: 'practice',
      capgeminiRelevance: 3,
      isVerified: true
    },

    // --- Java Fundamentals (10 questions) ---
    {
      category: 'technical-mcq',
      topic: 'Java Fundamentals',
      subtopic: 'String Pool',
      difficulty: 'medium',
      question: 'If `String s1 = "Capgemini";` and `String s2 = new String("Capgemini");`, what is the result of `s1 == s2`?',
      options: ['true', 'false', 'Compilation Error', 'Runtime Exception'],
      answer: 1,
      explanation: 's1 refers to an object in the String pool, while s2 refers to a new object created in heap memory. `==` checks reference equality, which is false.',
      whyOthersWrong: 'true would be for s1.equals(s2). There is no error.',
      tags: ['strings', 'memory'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Java Fundamentals',
      subtopic: 'Exception Handling',
      difficulty: 'medium',
      question: 'Which of these exceptions is a Checked Exception in Java?',
      options: ['NullPointerException', 'ArithmeticException', 'IOException', 'ArrayIndexOutOfBoundsException'],
      answer: 2,
      explanation: 'IOException is a checked exception. The compiler forces the programmer to either try-catch it or declare it in the method signature with `throws`.',
      whyOthersWrong: 'The others extend RuntimeException, making them unchecked exceptions.',
      tags: ['exceptions', 'java'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Java Fundamentals',
      subtopic: 'Collections',
      difficulty: 'medium',
      question: 'Which Collection class allows null keys and null values?',
      options: ['TreeMap', 'Hashtable', 'HashMap', 'ConcurrentHashMap'],
      answer: 2,
      explanation: 'HashMap allows one null key and multiple null values. It is not synchronized.',
      whyOthersWrong: 'Hashtable and ConcurrentHashMap do not allow any null keys or values. TreeMap does not allow null keys (throws NullPointerException).',
      tags: ['collections', 'map'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Java Fundamentals',
      subtopic: 'Final Keyword',
      difficulty: 'easy',
      question: 'What does the `final` keyword indicate when applied to a class?',
      options: ['The class cannot be instantiated', 'The class cannot be subclassed (inherited)', 'All methods in the class are abstract', 'The class can only have static variables'],
      answer: 1,
      explanation: 'A final class cannot be extended by any other class. For example, java.lang.String is a final class.',
      whyOthersWrong: 'Cannot be instantiated is for abstract classes. Abstract methods are in abstract classes/interfaces.',
      tags: ['final', 'oops'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Java Fundamentals',
      subtopic: 'Interfaces',
      difficulty: 'medium',
      question: 'Since Java 8, interfaces can have method implementations using which keyword?',
      options: ['static', 'default', 'Both static and default', 'None'],
      answer: 2,
      explanation: 'Since Java 8, interfaces can have fully implemented methods if they are declared as `default` or `static`.',
      whyOthersWrong: 'While default is true, static is also allowed. Prior to Java 8, interfaces could only have abstract methods.',
      tags: ['interfaces', 'java-8'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Java Fundamentals',
      subtopic: 'Multithreading',
      difficulty: 'medium',
      question: 'Which method must be implemented by a class implementing the Runnable interface?',
      options: ['start()', 'run()', 'execute()', 'main()'],
      answer: 1,
      explanation: 'The Runnable interface contains a single abstract method, `public void run()`, which contains the code that the thread will execute.',
      whyOthersWrong: 'start() is a method of the Thread class used to start thread execution, which internally calls run().',
      tags: ['threads', 'interfaces'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Java Fundamentals',
      subtopic: 'Method Overriding',
      difficulty: 'hard',
      question: 'Can you override a private method in Java?',
      options: ['Yes', 'No', 'Only in abstract classes', 'Only in the same package'],
      answer: 1,
      explanation: 'Private methods are not inherited by subclasses. Therefore, they cannot be overridden. Defining a method with the same signature in a subclass is method hiding, not overriding.',
      whyOthersWrong: 'Private methods are strictly bound to the class where they are declared.',
      tags: ['overriding', 'access-modifiers'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Java Fundamentals',
      subtopic: 'Immutability',
      difficulty: 'medium',
      question: 'Which of the following classes is mutable?',
      options: ['String', 'Integer', 'StringBuilder', 'Float'],
      answer: 2,
      explanation: 'StringBuilder is a mutable sequence of characters. Its content can be changed after object creation without creating a new object.',
      whyOthersWrong: 'String and all wrapper classes (Integer, Float, etc.) are immutable in Java.',
      tags: ['strings', 'mutability'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Java Fundamentals',
      subtopic: 'Collections',
      difficulty: 'medium',
      question: 'Which interface in the Java Collections Framework maintains insertion order?',
      options: ['Set', 'Queue', 'List', 'Map'],
      answer: 2,
      explanation: 'The List interface is an ordered collection that maintains the sequence in which elements were inserted. LinkedHashMap also maintains insertion order, but Map is not a collection interface.',
      whyOthersWrong: 'Set has no order (except LinkedHashSet). Queue prioritizes elements based on FIFO or comparators. Map is key-value based.',
      tags: ['collections', 'list'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Java Fundamentals',
      subtopic: 'Final keyword',
      difficulty: 'medium',
      question: 'What is the purpose of the finalize() method in Java?',
      options: ['To cleanly close a program', 'To declare a constant variable', 'To perform cleanup operations before an object is garbage collected', 'To prevent a method from being overridden'],
      answer: 2,
      explanation: 'The garbage collector calls finalize() right before destroying an object to release unmanaged resources. Note: it is deprecated since Java 9.',
      whyOthersWrong: 'final keyword is for constants/preventing overriding. System.exit() closes a program.',
      tags: ['garbage-collection', 'finalize'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 3,
      isVerified: true
    },

    // --- OOPs Concepts (15 questions) ---
    {
      category: 'technical-mcq',
      topic: 'OOPs Concepts',
      subtopic: 'Pillars of OOP',
      difficulty: 'easy',
      question: 'Wrapping data and methods into a single unit is known as:',
      options: ['Inheritance', 'Polymorphism', 'Encapsulation', 'Abstraction'],
      answer: 2,
      explanation: 'Encapsulation binds together data and functions that manipulate the data, keeping both safe from outside interference and misuse.',
      whyOthersWrong: 'Inheritance allows code reuse. Polymorphism allows one interface for many forms. Abstraction hides complex details.',
      tags: ['encapsulation', 'basics'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'OOPs Concepts',
      subtopic: 'Polymorphism',
      difficulty: 'medium',
      question: 'Which of the following represents compile-time polymorphism?',
      options: ['Method overriding', 'Method overloading', 'Virtual functions', 'Dynamic method dispatch'],
      answer: 1,
      explanation: 'Method overloading allows multiple methods with the same name but different parameters. The compiler determines which method to call at compile time (early binding).',
      whyOthersWrong: 'Method overriding and virtual functions represent run-time polymorphism (late binding).',
      tags: ['polymorphism', 'overloading'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'OOPs Concepts',
      subtopic: 'Constructors',
      difficulty: 'medium',
      question: 'Can a constructor be declared as virtual in C++?',
      options: ['Yes', 'No', 'Only in derived classes', 'Only in base classes'],
      answer: 1,
      explanation: 'A constructor cannot be virtual. When a constructor executes, the virtual table is not fully initialized, and the exact type of the object is known at the point of creation.',
      whyOthersWrong: 'Virtual destructors are allowed and often necessary, but virtual constructors are not possible in C++.',
      tags: ['constructors', 'virtual', 'cpp'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'OOPs Concepts',
      subtopic: 'Inheritance',
      difficulty: 'hard',
      question: 'The "Diamond Problem" occurs in which type of inheritance?',
      options: ['Single inheritance', 'Multiple inheritance', 'Multilevel inheritance', 'Hierarchical inheritance'],
      answer: 1,
      explanation: 'The diamond problem occurs in multiple inheritance when a class inherits from two classes that both inherit from a common base class, leading to ambiguity about which base class methods/data to use.',
      whyOthersWrong: 'Single, multilevel, and hierarchical inheritance paths do not converge, so they do not cause this ambiguity.',
      tags: ['inheritance', 'diamond-problem'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'OOPs Concepts',
      subtopic: 'Access Specifiers',
      difficulty: 'medium',
      question: 'Which access specifier makes members accessible only within the same class and its derived classes?',
      options: ['Private', 'Public', 'Protected', 'Internal'],
      answer: 2,
      explanation: 'Protected members are accessible within the class itself and by objects of derived classes, but not by the outside world.',
      whyOthersWrong: 'Private is only within the same class. Public is accessible everywhere.',
      tags: ['access-modifiers', 'protected'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'OOPs Concepts',
      subtopic: 'SOLID Principles',
      difficulty: 'hard',
      question: 'Which SOLID principle states that "Software entities should be open for extension, but closed for modification"?',
      options: ['Single Responsibility Principle', 'Open-Closed Principle', 'Liskov Substitution Principle', 'Dependency Inversion Principle'],
      answer: 1,
      explanation: 'The Open-Closed Principle (OCP) suggests you should be able to add new functionality without changing existing code, usually by using interfaces and abstract classes.',
      whyOthersWrong: 'SRP is one reason to change. LSP is about substituting base classes. DIP is about depending on abstractions.',
      tags: ['solid', 'design'],
      sourceType: 'capgemini-style',
      relevance: 'practice',
      capgeminiRelevance: 3,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'OOPs Concepts',
      subtopic: 'Destructors',
      difficulty: 'medium',
      question: 'Why is a virtual destructor needed in C++?',
      options: ['To make the destructor run faster', 'To allow multiple destructors in a class', 'To ensure derived class destructors are called when deleting through a base class pointer', 'To prevent memory leaks in the base class'],
      answer: 2,
      explanation: 'If a base class has a virtual destructor, deleting a derived class object via a base class pointer ensures the derived class destructor runs first, preventing resource leaks.',
      whyOthersWrong: 'It doesn\'t affect speed or allow multiple destructors. It prevents memory leaks in the derived class, not the base class.',
      tags: ['destructor', 'virtual', 'cpp'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'OOPs Concepts',
      subtopic: 'Constructors',
      difficulty: 'medium',
      question: 'What is a copy constructor?',
      options: ['A constructor that creates an exact copy of another class', 'A constructor that initializes an object using another object of the same class', 'A constructor with no arguments', 'A method to copy files'],
      answer: 1,
      explanation: 'A copy constructor initializes an object using another object of the exact same class, typically by copying reference values (shallow) or creating new memory (deep).',
      whyOthersWrong: 'No-argument constructor is a default constructor. It copies objects, not files or classes.',
      tags: ['constructors', 'copy-constructor'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'OOPs Concepts',
      subtopic: 'Abstraction',
      difficulty: 'easy',
      question: 'Hiding internal implementation details and showing only necessary features is called:',
      options: ['Encapsulation', 'Polymorphism', 'Inheritance', 'Abstraction'],
      answer: 3,
      explanation: 'Abstraction focuses on showing only the essential features to the user and hiding the background details or complex logic.',
      whyOthersWrong: 'Encapsulation is data binding. Polymorphism is many forms. Inheritance is extending existing code.',
      tags: ['abstraction', 'basics'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'OOPs Concepts',
      subtopic: 'Friend Functions',
      difficulty: 'medium',
      question: 'In C++, what is a friend function?',
      options: ['A function that can access private and protected members of a class', 'A function that belongs to a friend class', 'A function that is inherited by multiple classes', 'A virtual function'],
      answer: 0,
      explanation: 'A friend function is a function that is not a member of a class but is granted access to its private and protected members.',
      whyOthersWrong: 'Friend functions are independent functions, not inherited or virtual, and while friend classes exist, a friend function specifically grants access.',
      tags: ['friend-function', 'cpp'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'OOPs Concepts',
      subtopic: 'Static Members',
      difficulty: 'medium',
      question: 'A static method in a class can directly access:',
      options: ['Only instance variables', 'Only static variables', 'Both static and instance variables', 'Neither static nor instance variables'],
      answer: 1,
      explanation: 'Static methods belong to the class rather than instances. Therefore, they can only directly access other static members (variables or methods) of the class.',
      whyOthersWrong: 'They cannot access instance variables because an instance may not exist when the static method is called.',
      tags: ['static', 'methods'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'OOPs Concepts',
      subtopic: 'Inheritance',
      difficulty: 'easy',
      question: 'Which of the following establishes a "IS-A" relationship?',
      options: ['Aggregation', 'Composition', 'Inheritance', 'Association'],
      answer: 2,
      explanation: 'Inheritance models an "IS-A" relationship (e.g., a Dog IS-A Animal).',
      whyOthersWrong: 'Aggregation and Composition model "HAS-A" relationships (e.g., a Car HAS-A Engine).',
      tags: ['inheritance', 'is-a'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'OOPs Concepts',
      subtopic: 'Constructors',
      difficulty: 'medium',
      question: 'If no constructors are defined in a class, what happens?',
      options: ['Compilation error', 'The compiler provides a default no-argument constructor', 'The class cannot be instantiated', 'Runtime error'],
      answer: 1,
      explanation: 'If a class has no explicit constructors, the compiler automatically generates a default, parameterless constructor.',
      whyOthersWrong: 'There is no error. However, if you define any parameterized constructor, the compiler will NOT generate a default one.',
      tags: ['constructors', 'default'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'OOPs Concepts',
      subtopic: 'Interfaces',
      difficulty: 'medium',
      question: 'Which is true about Abstract Classes vs Interfaces?',
      options: ['A class can inherit multiple abstract classes but only one interface', 'An interface can have instance variables', 'A class can implement multiple interfaces but inherit only one abstract class', 'Abstract classes cannot have constructors'],
      answer: 2,
      explanation: 'In languages like Java and C#, multiple inheritance of classes is not allowed, but a class can implement multiple interfaces.',
      whyOthersWrong: 'Abstract classes CAN have constructors. Interfaces generally cannot have instance variables (only static constants).',
      tags: ['interfaces', 'abstract-classes'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'OOPs Concepts',
      subtopic: 'Polymorphism',
      difficulty: 'hard',
      question: 'What happens if a derived class hides a base class method with the same name but a different signature in C++?',
      options: ['It is method overloading', 'The base class method becomes inaccessible by default (Name Hiding)', 'Compilation error', 'The derived class method is ignored'],
      answer: 1,
      explanation: 'In C++, if you define a method in a derived class with the same name as a base class method, it hides ALL base class methods with that name, even if signatures differ.',
      whyOthersWrong: 'It is not overloading (which happens in the same scope). To use the base methods, one must use the `using` keyword.',
      tags: ['name-hiding', 'cpp'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },

    // --- Data Structures (15 questions) ---
    {
      category: 'technical-mcq',
      topic: 'Data Structures',
      subtopic: 'Arrays',
      difficulty: 'easy',
      question: 'What is the time complexity to access the nth element of an array?',
      options: ['O(n)', 'O(1)', 'O(log n)', 'O(n^2)'],
      answer: 1,
      explanation: 'Arrays use contiguous memory locations, so calculating the address of the nth element involves simple math and takes constant time O(1).',
      whyOthersWrong: 'O(n) is for searching in an unsorted array or accessing in a linked list.',
      tags: ['arrays', 'time-complexity'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Data Structures',
      subtopic: 'Binary Trees',
      difficulty: 'medium',
      question: 'What is the time complexity of searching in a balanced Binary Search Tree (BST)?',
      options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'],
      answer: 1,
      explanation: 'In a balanced BST, at each step we eliminate half the remaining nodes, giving us a time complexity proportional to the height of the tree, which is O(log n).',
      whyOthersWrong: 'O(n) is the worst case for an unbalanced/skewed BST. O(1) is for a Hash Table.',
      tags: ['bst', 'time-complexity', 'searching'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Data Structures',
      subtopic: 'Stacks',
      difficulty: 'medium',
      question: 'Which data structure is most suitable for evaluating postfix expressions?',
      options: ['Queue', 'Stack', 'Linked List', 'Binary Tree'],
      answer: 1,
      explanation: 'Stacks follow LIFO. Postfix evaluation is done by pushing operands to a stack and popping them when an operator is encountered.',
      whyOthersWrong: 'Queues follow FIFO. Trees represent expressions but Stacks are specifically used to evaluate them linearly.',
      tags: ['stacks', 'applications'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Data Structures',
      subtopic: 'Queues',
      difficulty: 'medium',
      question: 'In a circular queue implemented with an array of size N, what is the condition to check if the queue is full?',
      options: ['front == rear', 'rear == N-1', '(rear + 1) % N == front', 'front == (rear + 1) % N'],
      answer: 2,
      explanation: 'A circular queue is full when the next position of rear overlaps with the front index: (rear + 1) % N == front.',
      whyOthersWrong: 'front == rear indicates the queue is empty (depending on implementation). rear == N-1 is for a linear queue.',
      tags: ['queues', 'circular-queue'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Data Structures',
      subtopic: 'Linked Lists',
      difficulty: 'hard',
      question: 'Which pointer approach is best used to find the middle element of a singly linked list in a single pass?',
      options: ['Two pointers starting at opposite ends', 'Slow and Fast pointers', 'Using a hash map', 'Recursion'],
      answer: 1,
      explanation: 'Floyd\'s cycle-finding algorithm variant: Move the slow pointer by 1 step and the fast pointer by 2 steps. When the fast pointer reaches the end, the slow pointer is at the middle.',
      whyOthersWrong: 'Opposite ends require a doubly linked list. Hash map requires extra O(n) space.',
      tags: ['linked-list', 'algorithms'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Data Structures',
      subtopic: 'Hashing',
      difficulty: 'medium',
      question: 'What is the purpose of chaining in a hash table?',
      options: ['To speed up the hashing function', 'To resolve hash collisions', 'To reduce memory usage', 'To sort the elements'],
      answer: 1,
      explanation: 'Chaining is a collision resolution technique where each slot in the hash table points to a linked list of elements that hashed to the same slot.',
      whyOthersWrong: 'It increases memory usage slightly due to pointers. It has nothing to do with sorting or speeding up the hash function.',
      tags: ['hashing', 'collision-resolution'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Data Structures',
      subtopic: 'Graphs',
      difficulty: 'medium',
      question: 'Which algorithm is used to find the shortest path from a single source vertex to all other vertices in a weighted graph without negative cycles?',
      options: ['Kruskal\'s Algorithm', 'Prim\'s Algorithm', 'Dijkstra\'s Algorithm', 'Floyd-Warshall Algorithm'],
      answer: 2,
      explanation: 'Dijkstra\'s algorithm finds the shortest path tree from a single source to all other nodes.',
      whyOthersWrong: 'Kruskal and Prim find Minimum Spanning Trees. Floyd-Warshall finds all-pairs shortest paths and can handle negative edges.',
      tags: ['graphs', 'algorithms', 'shortest-path'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Data Structures',
      subtopic: 'Trees',
      difficulty: 'easy',
      question: 'Which traversal of a Binary Search Tree (BST) produces elements in sorted order?',
      options: ['Pre-order', 'In-order', 'Post-order', 'Level-order'],
      answer: 1,
      explanation: 'In-order traversal (Left, Root, Right) of a BST visits nodes in non-decreasing (sorted) order.',
      whyOthersWrong: 'Pre-order is useful for cloning trees. Post-order is useful for deleting trees. Level-order goes row by row.',
      tags: ['trees', 'traversal', 'bst'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Data Structures',
      subtopic: 'Heaps',
      difficulty: 'medium',
      question: 'In a Min-Heap, where is the smallest element located?',
      options: ['At a leaf node', 'At the root node', 'At the middle node', 'It varies randomly'],
      answer: 1,
      explanation: 'By the property of a min-heap, every parent node is less than or equal to its children, making the root the minimum element in the entire heap.',
      whyOthersWrong: 'Max-Heap has the largest element at the root.',
      tags: ['heaps', 'properties'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Data Structures',
      subtopic: 'Graphs',
      difficulty: 'medium',
      question: 'Which data structure is inherently used in Breadth-First Search (BFS) of a graph?',
      options: ['Stack', 'Queue', 'Priority Queue', 'Linked List'],
      answer: 1,
      explanation: 'BFS explores the graph layer by layer, exploring all immediate neighbors before going deeper. A Queue (FIFO) perfectly supports this ordering.',
      whyOthersWrong: 'DFS uses a Stack (LIFO). Dijkstra\'s uses a Priority Queue.',
      tags: ['graphs', 'bfs'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Data Structures',
      subtopic: 'Trees',
      difficulty: 'hard',
      question: 'What is the key property of an AVL Tree?',
      options: ['Every node has exactly 0 or 2 children', 'All leaf nodes are at the same level', 'The difference in heights of the left and right subtrees for any node is at most 1', 'It can store duplicates efficiently'],
      answer: 2,
      explanation: 'An AVL tree is a strictly height-balanced binary search tree. The balance factor (height of left subtree - height of right subtree) must be -1, 0, or 1.',
      whyOthersWrong: '0 or 2 children is a strict/full binary tree. All leaves at same level implies a perfect binary tree.',
      tags: ['trees', 'avl'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Data Structures',
      subtopic: 'Sorting Algorithms',
      difficulty: 'medium',
      question: 'Which sorting algorithm has the best average-case time complexity?',
      options: ['Bubble Sort', 'Insertion Sort', 'Merge Sort', 'Selection Sort'],
      answer: 2,
      explanation: 'Merge Sort has an average and worst-case time complexity of O(n log n). The others are O(n^2).',
      whyOthersWrong: 'Bubble, Insertion, and Selection sorts take O(n^2) on average.',
      tags: ['algorithms', 'sorting'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Data Structures',
      subtopic: 'Linked Lists',
      difficulty: 'easy',
      question: 'What is the main advantage of a Linked List over an Array?',
      options: ['Faster random access', 'Dynamic size and efficient insertions/deletions', 'Less memory usage', 'Better cache locality'],
      answer: 1,
      explanation: 'Linked lists do not require contiguous memory, allowing dynamic resizing and O(1) insertions/deletions if the pointer location is known.',
      whyOthersWrong: 'Arrays have faster random access (O(1)) and better cache locality. Linked lists use MORE memory due to pointers.',
      tags: ['linked-list', 'arrays'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Data Structures',
      subtopic: 'Stacks',
      difficulty: 'medium',
      question: 'If elements "A", "B", "C", "D" are placed in a stack and are deleted one at a time, what will be the order of removal?',
      options: ['A B C D', 'D C B A', 'D A B C', 'A D C B'],
      answer: 1,
      explanation: 'A stack operates on the Last-In-First-Out (LIFO) principle. Since D was the last to be pushed, it will be the first popped.',
      whyOthersWrong: 'A B C D is the order for a Queue (FIFO).',
      tags: ['stacks', 'lifo'],
      sourceType: 'capgemini-style',
      relevance: 'practice',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Data Structures',
      subtopic: 'Hashing',
      difficulty: 'hard',
      question: 'What is the "load factor" in a Hash Table?',
      options: ['The maximum size of the hash table', 'The number of elements divided by the table size', 'The number of collisions', 'The time taken by the hash function'],
      answer: 1,
      explanation: 'The load factor is the ratio of the number of entries (n) to the number of buckets/slots (k) in the table. It measures how full the table is.',
      whyOthersWrong: 'It determines when to resize the table to maintain O(1) access time.',
      tags: ['hashing', 'load-factor'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },

    // --- DBMS & SQL (15 questions) ---
    {
      category: 'technical-mcq',
      topic: 'DBMS & SQL',
      subtopic: 'ACID Properties',
      difficulty: 'easy',
      question: 'In database transaction management, what does the "A" in ACID stand for?',
      options: ['Accuracy', 'Availability', 'Atomicity', 'Authentication'],
      answer: 2,
      explanation: 'Atomicity means "all or nothing". Either all operations in a transaction complete successfully, or none do.',
      whyOthersWrong: 'ACID stands for Atomicity, Consistency, Isolation, and Durability.',
      tags: ['dbms', 'acid'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'DBMS & SQL',
      subtopic: 'Normalization',
      difficulty: 'medium',
      question: 'Which normal form is concerned with removing transitive dependencies?',
      options: ['First Normal Form (1NF)', 'Second Normal Form (2NF)', 'Third Normal Form (3NF)', 'Boyce-Codd Normal Form (BCNF)'],
      answer: 2,
      explanation: '3NF dictates that a table must be in 2NF and have no transitive partial dependencies (non-prime attributes must only depend on the primary key).',
      whyOthersWrong: '1NF handles atomicity. 2NF removes partial dependencies. BCNF ensures every determinant is a candidate key.',
      tags: ['normalization', '3nf'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'DBMS & SQL',
      subtopic: 'JOINs',
      difficulty: 'medium',
      question: 'Which SQL JOIN returns all rows from both tables, with NULL values where there is no match?',
      options: ['INNER JOIN', 'LEFT JOIN', 'RIGHT JOIN', 'FULL OUTER JOIN'],
      answer: 3,
      explanation: 'FULL OUTER JOIN combines the results of both LEFT and RIGHT joins, returning all rows from both tables and filling in NULLs for non-matching rows.',
      whyOthersWrong: 'LEFT JOIN returns all from the left table. INNER JOIN only returns matching rows.',
      tags: ['sql', 'joins'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'DBMS & SQL',
      subtopic: 'Keys',
      difficulty: 'medium',
      question: 'A key that uniquely identifies a record in another table is called a:',
      options: ['Primary Key', 'Foreign Key', 'Candidate Key', 'Super Key'],
      answer: 1,
      explanation: 'A Foreign Key is a field in one table that uniquely identifies a row of another table, establishing a relationship between the two tables.',
      whyOthersWrong: 'Primary key identifies records in its OWN table. Candidate keys are potential primary keys.',
      tags: ['keys', 'relational-model'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'DBMS & SQL',
      subtopic: 'SQL Clauses',
      difficulty: 'medium',
      question: 'Which clause is used to filter the results of a GROUP BY operation?',
      options: ['WHERE', 'ORDER BY', 'HAVING', 'FILTER'],
      answer: 2,
      explanation: 'The HAVING clause was added to SQL because the WHERE clause cannot be used with aggregate functions (like SUM, COUNT, MAX).',
      whyOthersWrong: 'WHERE filters individual rows BEFORE grouping. HAVING filters groups AFTER grouping.',
      tags: ['sql', 'having', 'group-by'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'DBMS & SQL',
      subtopic: 'Transactions',
      difficulty: 'hard',
      question: 'What is a deadlock in a DBMS?',
      options: ['When a transaction takes too long to execute', 'When two or more transactions are waiting indefinitely for one another to release locks', 'When the database crashes during a transaction', 'When a user enters the wrong password multiple times'],
      answer: 1,
      explanation: 'A deadlock occurs when Transaction A holds a lock needed by Transaction B, and Transaction B holds a lock needed by Transaction A, causing a permanent freeze.',
      whyOthersWrong: 'The others represent timeouts, system failures, or authentication issues, not deadlocks.',
      tags: ['dbms', 'transactions', 'deadlock'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'DBMS & SQL',
      subtopic: 'Commands',
      difficulty: 'easy',
      question: 'Which of the following is a DDL (Data Definition Language) command?',
      options: ['SELECT', 'INSERT', 'CREATE', 'UPDATE'],
      answer: 2,
      explanation: 'CREATE is a DDL command used to define the database structure or schema.',
      whyOthersWrong: 'SELECT, INSERT, and UPDATE are DML (Data Manipulation Language) commands used to manipulate data.',
      tags: ['sql', 'ddl', 'dml'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'DBMS & SQL',
      subtopic: 'Indexing',
      difficulty: 'medium',
      question: 'What is the primary purpose of indexing in a database?',
      options: ['To conserve disk space', 'To prevent duplicate records', 'To speed up data retrieval operations', 'To automatically backup data'],
      answer: 2,
      explanation: 'Indexes function like an index in a book. They allow the database engine to find data faster without scanning the entire table (full table scan).',
      whyOthersWrong: 'Indexes actually CONSUME disk space. Unique constraints prevent duplicates.',
      tags: ['dbms', 'indexing', 'performance'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'DBMS & SQL',
      subtopic: 'SQL Clauses',
      difficulty: 'easy',
      question: 'Which keyword is used in SQL to sort the result set?',
      options: ['SORT BY', 'ORDER BY', 'GROUP BY', 'ALIGN BY'],
      answer: 1,
      explanation: 'The ORDER BY keyword is used to sort the result-set in ascending (ASC) or descending (DESC) order.',
      whyOthersWrong: 'GROUP BY aggregates rows. SORT BY and ALIGN BY are not standard SQL keywords.',
      tags: ['sql', 'order-by'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'DBMS & SQL',
      subtopic: 'Keys',
      difficulty: 'medium',
      question: 'Can a table have multiple Primary Keys?',
      options: ['Yes', 'No', 'Yes, but only in NoSQL databases', 'Yes, but only if they are numeric'],
      answer: 1,
      explanation: 'A table can only have ONE Primary Key. However, a Primary Key can be composite, meaning it consists of multiple columns acting together as a single key.',
      whyOthersWrong: 'By definition, a relational table has exactly zero or one primary key constraint.',
      tags: ['dbms', 'primary-key'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'DBMS & SQL',
      subtopic: 'ACID Properties',
      difficulty: 'hard',
      question: 'Which property ensures that once a transaction has been committed, it will remain so, even in the event of power loss or crashes?',
      options: ['Atomicity', 'Consistency', 'Isolation', 'Durability'],
      answer: 3,
      explanation: 'Durability guarantees that once a transaction is committed, the changes are saved permanently to non-volatile storage (like a hard drive).',
      whyOthersWrong: 'Atomicity is all-or-nothing. Consistency ensures valid state transitions. Isolation prevents concurrent transactions from interfering.',
      tags: ['dbms', 'acid', 'durability'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'DBMS & SQL',
      subtopic: 'SQL Functions',
      difficulty: 'medium',
      question: 'Which SQL function returns the number of rows that match a specified criterion?',
      options: ['SUM()', 'COUNT()', 'MAX()', 'ROWS()'],
      answer: 1,
      explanation: 'COUNT() is an aggregate function that returns the number of rows returned by a query.',
      whyOthersWrong: 'SUM totals numeric columns. MAX finds the highest value.',
      tags: ['sql', 'aggregate-functions'],
      sourceType: 'capgemini-style',
      relevance: 'practice',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'DBMS & SQL',
      subtopic: 'Normalization',
      difficulty: 'hard',
      question: 'Which of the following is true for a table in 2NF?',
      options: ['It must be in 1NF and have no partial dependencies', 'It must have no transitive dependencies', 'Every determinant must be a candidate key', 'It allows multi-valued attributes'],
      answer: 0,
      explanation: 'Second Normal Form (2NF) requires a table to be in 1NF (atomic values) AND every non-prime attribute must be fully functionally dependent on the entire primary key.',
      whyOthersWrong: 'No transitive dependencies is 3NF. Determinant = candidate key is BCNF.',
      tags: ['dbms', 'normalization', '2nf'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'DBMS & SQL',
      subtopic: 'Joins',
      difficulty: 'medium',
      question: 'What is a Cross Join?',
      options: ['A join that returns matching rows from both tables', 'A join that combines tables based on a common column', 'A join that produces the Cartesian product of two tables', 'A self-join on the same table'],
      answer: 2,
      explanation: 'A CROSS JOIN returns the Cartesian product of rows from tables in the join. If table A has M rows and B has N rows, the result has M*N rows.',
      whyOthersWrong: 'INNER JOIN relies on common columns. It is not necessarily a self-join.',
      tags: ['sql', 'cross-join'],
      sourceType: 'capgemini-style',
      relevance: 'practice',
      capgeminiRelevance: 3,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'DBMS & SQL',
      subtopic: 'SQL Commands',
      difficulty: 'medium',
      question: 'What is the difference between TRUNCATE and DELETE?',
      options: ['TRUNCATE is DML, DELETE is DDL', 'DELETE removes specific rows and can be rolled back; TRUNCATE removes all rows quickly and cannot be rolled back', 'TRUNCATE removes table structure, DELETE removes data', 'No difference'],
      answer: 1,
      explanation: 'TRUNCATE is a DDL command that resets the table by removing all rows (and resets identity seeds), usually bypassing the transaction log, so it cannot be easily rolled back. DELETE is DML, logs each row deletion, and can be rolled back.',
      whyOthersWrong: 'Removing table structure is DROP. TRUNCATE is DDL, DELETE is DML.',
      tags: ['sql', 'truncate-delete'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },

    // --- Operating Systems (10 questions) ---
    {
      category: 'technical-mcq',
      topic: 'Operating Systems',
      subtopic: 'Process vs Thread',
      difficulty: 'medium',
      question: 'Which of the following is shared among threads of the same process?',
      options: ['Stack', 'Registers', 'Data Section (Heap & Globals)', 'Program Counter'],
      answer: 2,
      explanation: 'Threads within the same process share the process\'s data section, code section, and OS resources like open files. However, each thread has its own Stack, Registers, and Program Counter.',
      whyOthersWrong: 'Stacks and registers MUST be isolated so threads can execute independently.',
      tags: ['os', 'threads', 'process'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Operating Systems',
      subtopic: 'Deadlocks',
      difficulty: 'medium',
      question: 'Which algorithm is used for Deadlock Avoidance?',
      options: ['Round Robin', 'Banker\'s Algorithm', 'Elevator Algorithm', 'Peterson\'s Algorithm'],
      answer: 1,
      explanation: 'Dijkstra\'s Banker\'s Algorithm avoids deadlocks by simulating resource allocation to ensure the system remains in a "safe state" before granting requests.',
      whyOthersWrong: 'Round Robin is CPU scheduling. Elevator is disk scheduling. Peterson\'s is for critical section synchronization.',
      tags: ['os', 'deadlocks', 'bankers-algorithm'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Operating Systems',
      subtopic: 'CPU Scheduling',
      difficulty: 'medium',
      question: 'Which CPU scheduling algorithm is most prone to the "Starvation" problem?',
      options: ['Round Robin', 'First Come First Serve (FCFS)', 'Priority Scheduling', 'Shortest Job First (Preemptive)'],
      answer: 2,
      explanation: 'In Priority Scheduling, a low-priority process might wait indefinitely if higher-priority processes keep arriving (Starvation). This is solved by "Aging".',
      whyOthersWrong: 'Round Robin is fair. FCFS doesn\'t starve (just causes convoy effect).',
      tags: ['os', 'scheduling', 'starvation'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Operating Systems',
      subtopic: 'Memory Management',
      difficulty: 'medium',
      question: 'What is "Thrashing" in an Operating System?',
      options: ['When a process executes rapidly', 'When the CPU spends more time swapping pages than executing instructions', 'When the hard disk crashes', 'When memory is completely full'],
      answer: 1,
      explanation: 'Thrashing occurs when a computer\'s virtual memory subsystem is in a constant state of paging, rapidly exchanging data in memory for data on disk, causing performance to plummet.',
      whyOthersWrong: 'It is specifically the excessive paging activity, not a physical disk crash or fast execution.',
      tags: ['os', 'memory-management', 'thrashing'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Operating Systems',
      subtopic: 'Page Replacement',
      difficulty: 'hard',
      question: 'Which page replacement algorithm suffers from Belady\'s Anomaly?',
      options: ['Least Recently Used (LRU)', 'First In First Out (FIFO)', 'Optimal Page Replacement', 'Second Chance Algorithm'],
      answer: 1,
      explanation: 'Belady\'s Anomaly is a phenomenon in FIFO page replacement where increasing the number of page frames results in an INCREASE in the number of page faults.',
      whyOthersWrong: 'LRU and Optimal are stack algorithms and never suffer from Belady\'s anomaly.',
      tags: ['os', 'page-replacement', 'fifo'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Operating Systems',
      subtopic: 'Concepts',
      difficulty: 'easy',
      question: 'What is a Context Switch?',
      options: ['Changing the OS theme', 'Saving the state of an old process and loading the saved state for a new process', 'Switching from user mode to kernel mode', 'Restarting the computer'],
      answer: 1,
      explanation: 'A context switch is the process of storing the state of an active process or thread so that it can be resumed later, and loading the state of another process to run.',
      whyOthersWrong: 'Mode switch (user to kernel) is different from a context switch between two processes.',
      tags: ['os', 'context-switch'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Operating Systems',
      subtopic: 'Synchronization',
      difficulty: 'hard',
      question: 'What is a Semaphore?',
      options: ['A hardware register', 'A specialized file system', 'An integer variable used for signaling among processes', 'A CPU scheduling algorithm'],
      answer: 2,
      explanation: 'A semaphore is a synchronization tool (usually an integer variable) used to manage concurrent processes and avoid race conditions in critical sections.',
      whyOthersWrong: 'It is a software construct for synchronization, not hardware, file system, or scheduling.',
      tags: ['os', 'synchronization', 'semaphores'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Operating Systems',
      subtopic: 'Memory Management',
      difficulty: 'medium',
      question: 'In paging, physical memory is divided into fixed-sized blocks called:',
      options: ['Pages', 'Segments', 'Frames', 'Sectors'],
      answer: 2,
      explanation: 'Physical memory is broken down into fixed-sized blocks called "Frames". Logical memory is divided into blocks of the same size called "Pages".',
      whyOthersWrong: 'Pages are logical. Segments are variable-sized. Sectors are disk divisions.',
      tags: ['os', 'paging', 'memory'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Operating Systems',
      subtopic: 'Deadlocks',
      difficulty: 'medium',
      question: 'Which of the following is NOT a necessary condition for a deadlock?',
      options: ['Mutual Exclusion', 'Hold and Wait', 'No Preemption', 'Starvation'],
      answer: 3,
      explanation: 'The four necessary conditions for deadlock are: Mutual Exclusion, Hold and Wait, No Preemption, and Circular Wait. Starvation is a different issue.',
      whyOthersWrong: 'Starvation means a process waits indefinitely, but it does not freeze the whole system like a deadlock.',
      tags: ['os', 'deadlocks'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Operating Systems',
      subtopic: 'CPU Scheduling',
      difficulty: 'easy',
      question: 'Round Robin scheduling relies heavily on a hardware device called:',
      options: ['Timer', 'Disk Controller', 'Cache Memory', 'GPU'],
      answer: 0,
      explanation: 'Round Robin relies on a hardware timer to interrupt the CPU after a specified time quantum (slice) expires, forcing a context switch.',
      whyOthersWrong: 'Without a timer interrupt, the OS cannot preempt the currently running process.',
      tags: ['os', 'scheduling', 'round-robin'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 3,
      isVerified: true
    },

    // --- Computer Networks (10 questions) ---
    {
      category: 'technical-mcq',
      topic: 'Computer Networks',
      subtopic: 'OSI Model',
      difficulty: 'easy',
      question: 'Which layer of the OSI model is responsible for logical addressing (IP addressing)?',
      options: ['Data Link Layer', 'Network Layer', 'Transport Layer', 'Application Layer'],
      answer: 1,
      explanation: 'The Network Layer (Layer 3) handles routing and logical addressing (IP addresses) to move data across networks.',
      whyOthersWrong: 'Data Link uses MAC addresses. Transport uses Ports. Application uses protocols like HTTP.',
      tags: ['networks', 'osi', 'network-layer'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Computer Networks',
      subtopic: 'TCP vs UDP',
      difficulty: 'medium',
      question: 'Which characteristic describes UDP (User Datagram Protocol)?',
      options: ['Connection-oriented', 'Reliable data transfer', 'Connectionless and fast', 'Three-way handshake'],
      answer: 2,
      explanation: 'UDP is a connectionless, best-effort protocol that does not guarantee delivery, making it faster and suitable for streaming and gaming.',
      whyOthersWrong: 'Connection-oriented, reliable, and 3-way handshake describe TCP.',
      tags: ['networks', 'udp', 'tcp'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Computer Networks',
      subtopic: 'Protocols',
      difficulty: 'medium',
      question: 'What is the purpose of the ARP protocol?',
      options: ['To map domain names to IP addresses', 'To map IP addresses to MAC addresses', 'To dynamically assign IP addresses', 'To secure network traffic'],
      answer: 1,
      explanation: 'Address Resolution Protocol (ARP) translates logical IP addresses into physical MAC addresses within a local network.',
      whyOthersWrong: 'DNS maps domains to IPs. DHCP assigns IPs dynamically. TLS/SSL secures traffic.',
      tags: ['networks', 'arp'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Computer Networks',
      subtopic: 'IP Addressing',
      difficulty: 'medium',
      question: 'Which IPv4 address class is typically used for large organizations, providing 16 million hosts per network?',
      options: ['Class A', 'Class B', 'Class C', 'Class D'],
      answer: 0,
      explanation: 'Class A provides 8 bits for the network ID and 24 bits for the host ID, supporting 2^24 - 2 (approx 16.7 million) hosts.',
      whyOthersWrong: 'Class B gives ~65K hosts. Class C gives 254 hosts. Class D is for multicasting.',
      tags: ['networks', 'ip-address'],
      sourceType: 'capgemini-style',
      relevance: 'practice',
      capgeminiRelevance: 3,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Computer Networks',
      subtopic: 'Protocols',
      difficulty: 'easy',
      question: 'Which protocol operates at port 443?',
      options: ['HTTP', 'FTP', 'HTTPS', 'SSH'],
      answer: 2,
      explanation: 'HTTPS (HTTP Secure) uses TCP port 443 by default.',
      whyOthersWrong: 'HTTP uses 80. FTP uses 20/21. SSH uses 22.',
      tags: ['networks', 'ports', 'https'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Computer Networks',
      subtopic: 'OSI Model',
      difficulty: 'medium',
      question: 'At which OSI layer do Routers primarily operate?',
      options: ['Physical Layer', 'Data Link Layer', 'Network Layer', 'Transport Layer'],
      answer: 2,
      explanation: 'Routers operate at the Network Layer (Layer 3). They read IP addresses to determine the best path to forward packets.',
      whyOthersWrong: 'Switches operate at Layer 2 (Data Link). Hubs are Layer 1 (Physical).',
      tags: ['networks', 'routers', 'osi'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Computer Networks',
      subtopic: 'Protocols',
      difficulty: 'medium',
      question: 'What protocol dynamically assigns an IP address to a client device?',
      options: ['DNS', 'DHCP', 'SMTP', 'ICMP'],
      answer: 1,
      explanation: 'Dynamic Host Configuration Protocol (DHCP) automatically assigns IP addresses and network parameters to devices.',
      whyOthersWrong: 'DNS resolves names. SMTP sends emails. ICMP handles error messages (like ping).',
      tags: ['networks', 'dhcp'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Computer Networks',
      subtopic: 'Topologies',
      difficulty: 'easy',
      question: 'In which network topology does every node connect to a central hub or switch?',
      options: ['Ring', 'Bus', 'Star', 'Mesh'],
      answer: 2,
      explanation: 'In a Star topology, all devices are connected to a central device (hub/switch). If the hub fails, the network fails.',
      whyOthersWrong: 'Ring connects sequentially. Bus uses a single backbone cable. Mesh connects everyone to everyone.',
      tags: ['networks', 'topology'],
      sourceType: 'capgemini-style',
      relevance: 'practice',
      capgeminiRelevance: 3,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Computer Networks',
      subtopic: 'IP Addressing',
      difficulty: 'hard',
      question: 'What is the loopback address in IPv4?',
      options: ['192.168.1.1', '255.255.255.255', '127.0.0.1', '0.0.0.0'],
      answer: 2,
      explanation: '127.0.0.1 (and the entire 127.x.x.x block) is reserved for loopback testing to the local machine (localhost).',
      whyOthersWrong: '192.168.x is private. 255.255.255.255 is broadcast. 0.0.0.0 is an unroutable meta-address.',
      tags: ['networks', 'ip'],
      sourceType: 'capgemini-style',
      relevance: 'high-priority',
      capgeminiRelevance: 4,
      isVerified: true
    },
    {
      category: 'technical-mcq',
      topic: 'Computer Networks',
      subtopic: 'Data Link Layer',
      difficulty: 'medium',
      question: 'What is a MAC address?',
      options: ['A 32-bit logical address', 'A 128-bit logical address', 'A 48-bit physical address', 'A domain name mapping'],
      answer: 2,
      explanation: 'A Media Access Control (MAC) address is a 48-bit hardware address permanently burned into a network interface card (NIC) by the manufacturer.',
      whyOthersWrong: '32-bit logical is IPv4. 128-bit logical is IPv6.',
      tags: ['networks', 'mac'],
      sourceType: 'capgemini-style',
      relevance: 'must-know',
      capgeminiRelevance: 5,
      isVerified: true
    }
  ];

  try {
    await Question.insertMany(questions);
    console.log(`Successfully inserted \${questions.length} Technical MCQs!`);
  } catch (error) {
    console.error('Error seeding Technical MCQs:', error);
  }
};


